=== Paulo-B/DWeb2019/TP2/PR.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="PR">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="header"/>
        <xs:element ref="team"/>
        <xs:element ref="abs"/>
        <xs:element ref="deliverables"/>
        <xs:element ref="data"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="header">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="keyname"/>
        <xs:element ref="title"/>
        <xs:element minOccurs="0" ref="subtitle"/>
        <xs:element ref="dataB"/>
        <xs:element ref="dataE"/>
        <xs:element ref="supervisor"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="keyname" type="xs:string"/>
  <xs:element name="title" type="xs:string"/>
  <xs:element name="subtitle" type="xs:string"/>
  <xs:element name="dataB">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="data"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="dataE">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="data"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="supervisor">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="link"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="link">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="texto"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.link"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.link">
    <xs:attribute name="url"/>
  </xs:attributeGroup>
  <xs:element name="texto" type="xs:string"/>
  <xs:element name="team">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="elemento"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="elemento">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="id"/>
        <xs:element ref="texto"/>
        <xs:element ref="mail"/>
        <xs:element minOccurs="0" ref="git"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="id" type="xs:string"/>
  <xs:element name="mail">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="link"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="git">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="link"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="abs">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="bold"/>
        <xs:element ref="italico"/>
        <xs:element ref="link"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="deliverables">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="link"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="data" type="xs:string"/>
  <xs:element name="bold" type="xs:string"/>
  <xs:element name="italico" type="xs:string"/>
</xs:schema>

=== Paulo-B/DWeb2019/TP2/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<PR xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/home/apocas/Desktop/EngenhariaInformatica/DAW/PR.xsd">
    <header>
        <keyname>TP2</keyname>
        <title>PR DTD,Arqueossitios DTD e Exercicios de XPATH </title>
        <subtitle>
            Relatorio do TP2 inserido na cadeira de DAW
        </subtitle>
        <dataB>
            <data>26 Setembro 2019</data>
        </dataB>
        <dataE>
            <data>26 Setembro 2019</data>
        </dataE>
        <supervisor>
            <link url="http://www.di.uminho.pt/~jcr">
                <texto>José Carlos Ramalho</texto>
            </link>
        </supervisor>
    </header>
    <team>
        <elemento>
            <id>A81139</id>
            <texto>Paulo Jorge Bento Rosa</texto>
            <mail>
                <link>
                    <texto>a81139@alunos.uminho.pt</texto>
                </link>
            </mail>
            <git>
                <link url="https://github.com/Paulo-B/DWeb2019">
                    <texto>Paulo-B</texto>
                </link>
            </git>
        </elemento>
    </team>
    <abs>
        O DTD definido permite definir a estrutura deste Project Record permitindo de uma forma mais standard tratar a informaçao.
        Adjuntamente tambem se encontra outro DTD gerado a partir do XML exemplo para arqueossitio atraves do Oxygen Editor solicitado na <link url="http://www4.di.uminho.pt/~jcr/XML/CURSOS/PED2008/fichas/ficha3/e7.html">
            <texto>Ficha 3- Exercicio 7</texto>
        </link>.Finalmente tambem existe um ficheiro que responde aos exercicios de querie sobre o mesmo que se encontra em <link url="http://www4.di.uminho.pt/~jcr/XML/CURSOS/PED2008/fichas/ficha3/e6.html">
            <texto>Ficha 3 - Exercicio 6</texto>
        </link>
    </abs>
    <deliverables>
        <link url="arq.dtd">
            <texto>DTD dos Arqueossitios</texto>
        </link>
        <link url="PR.dtd">
            <texto>DTD do Project Record</texto>
        </link>
        <link url="queries">
            <texto>Queries XPath</texto>
        </link>
        <link url="arq.xml">
            <texto>XML exemplo dos arqueossitios</texto>
        </link>
        <link url="PR.xsd">
            <texto>XML Schema do PR</texto>
        </link>
    </deliverables>
    <data>26-09-2019</data>
</PR>
